<?php
$page_title = 'Daftar Jurnal - KSM Education';
include 'components/header.php';
include 'components/sidebar.php';
?>


    <!-- Main Content -->
    <div class="container">
      <!--  FIX: Filter & Search Section -->
      <section class="filter-section">
        <!-- Row 1: Icon Sort + Search Box -->
        <div class="filter-row-top">
          <!-- Icon Sort Dropdown -->
          <div class="sort-dropdown">
            <button class="btn-icon-sort" type="button" id="btnSort">
              <i data-feather="filter"></i>
            </button>
            <div class="sort-menu" id="sortMenu">
              <button data-sort="newest" class="sort-item active">
                <i data-feather="clock"></i>
                Terbaru
              </button>
              <button data-sort="oldest" class="sort-item">
                <i data-feather="calendar"></i>
                Terlama
              </button>
              <button data-sort="title" class="sort-item">
                <i data-feather="type"></i>
                Judul A-Z
              </button>
              <button data-sort="views" class="sort-item">
                <i data-feather="eye"></i>
                Paling Populer
              </button>
            </div>
          </div>

          <!-- Search Box -->
          <div class="search-box">
            <i data-feather="search"></i>
            <input type="text" placeholder="Cari jurnal..." id="searchInput" />
          </div>
        </div>

        <!-- Row 2: Total Counter -->
        <div class="filter-row-bottom">
          <div class="filter-stats">
            <span id="totalJournals">0</span> Artikel
          </div>
        </div>
      </section>

      <!-- Back Button -->
      <section class="back-section">
        <a href="./dashboard_admin.php" class="btn-back">
          <i data-feather="arrow-left"></i>
        </a>
      </section>

      <!-- Journal List Section -->
      <section id="journal" class="journal-list-full">
        <div id="journalContainer" class="list-view">
          <!-- Journal items will be generated by pagination.js -->
        </div>
      </section>

      <!-- Pagination -->
      <section class="pagination-section">
        <div id="pagination" class="pagination"></div>
      </section>
    </div>

    <!-- Share Modal -->
    <div id="shareModal" class="modal">
      <div class="modal-overlay"></div>
      <div class="modal-content" style="max-width: 400px">
        <button type="button" class="close-modal" onclick="closeShareModal()">
          <i data-feather="x"></i>
        </button>
        <h2 style="margin-bottom: 20px">Bagikan Jurnal</h2>
        <div style="display: flex; flex-direction: column; gap: 12px">
          <input
            type="text"
            id="shareUrlInput"
            readonly
            style="
              padding: 12px;
              border: 1px solid #ddd;
              border-radius: 6px;
              font-size: 14px;
            "
          />
          <button onclick="copyShareLink()" class="share-btn copy">
            <i data-feather="copy"></i> Copy Link
          </button>
          <button onclick="shareToWhatsApp()" class="share-btn wa">
            <i data-feather="message-circle"></i> Share ke WhatsApp
          </button>
          <button onclick="shareToFacebook()" class="share-btn fb">
            <i data-feather="facebook"></i> Share ke Facebook
          </button>
          <button onclick="shareToTwitter()" class="share-btn x">
            <i data-feather="x"></i> Share ke X
          </button>
        </div>
      </div>
    </div>

    <div id="editModal" class="modal">
      <div class="modal-overlay"></div>
      <div class="modal-content">
        <button id="closeEditModal" type="button" class="modal-close">
          &times;
        </button>

        <h2>Edit Jurnal</h2>

        <form id="editForm">
          <input type="hidden" id="editJournalId" />

          <div class="form-group">
            <label for="editJudulJurnal">Judul Jurnal</label>
            <input type="text" id="editJudulJurnal" required />
          </div>

          <div class="form-group">
            <label for="editEmail">Email</label>
            <input type="email" id="editEmail" />
          </div>

          <div class="form-group">
            <label for="editKontak">Kontak</label>
            <input type="text" id="editKontak" />
          </div>

          <div class="form-group" id="editVolumeGroup">
            <label for="editVolume">Volume</label>
            <input type="text" id="editVolume" />
          </div>

          <div class="form-group">
            <label for="editAbstrak">Abstrak</label>
            <textarea id="editAbstrak" rows="5"></textarea>
          </div>

          <!-- Authors -->
          <div class="form-group">
            <label>Penulis</label>
            <div id="editAuthorsContainer">
              <div class="author-input-group">
                <input
                  type="text"
                  class="author-input"
                  placeholder="Nama Penulis 1"
                  required
                />
                <button
                  type="button"
                  class="btn-remove-author"
                  style="display: none"
                >
                  <i data-feather="x"></i>
                </button>
              </div>
            </div>
            <button type="button" id="editAddAuthorBtn" class="btn-small">
              + Tambah Penulis
            </button>
          </div>

          <!-- Pengurus -->
          <div class="form-group" id="editPengurusGroup">
            <label>Pengurus</label>
            <div id="editPengurusContainer"></div>
            <button type="button" id="editAddPengurusBtn" class="btn-small">
              + Tambah Pengurus
            </button>
          </div>

          <!-- Tags -->
          <div class="form-group">
            <label>Tags</label>
            <div id="editTagsContainer" class="tags-container"></div>
            <div class="tag-input-row">
              <input
                type="text"
                id="editTagInput"
                placeholder="Tambahkan tag"
              />
              <button type="button" id="editAddTagBtn" class="btn-small">
                + Tambah
              </button>
            </div>
          </div>

          <!-- File & Cover -->
          <div class="form-group">
            <label for="editFileInput"
              >File PDF (opsional, biarkan kosong jika tidak diubah)</label
            >
            <input type="file" id="editFileInput" accept="application/pdf" />
          </div>

          <div class="form-group">
            <label for="editCoverInput">Cover (opsional)</label>
            <input type="file" id="editCoverInput" accept="image/*" />
          </div>

          <div class="form-actions">
            <button type="button" id="cancelEdit" class="btn-secondary">
              Batal
            </button>
            <button type="submit" class="btn-primary">Simpan Perubahan</button>
          </div>
        </form>
      </div>
    </div>

<?php
$extra_scripts = <<<'EOT'
<script src="../js/statistic.js"></script>
    <script src="../js/file_upload.js"></script>
    <script src="../js/pagination_admin.js?v=20260321"></script>
    <script src="../js/jurnal.js?v=20260321"></script>
    <script src="../js/social.js"></script>
    <script>
      if (typeof feather !== 'undefined') feather.replace();
    </script>
  
EOT;
include 'components/footer.php';
?>
