<?php
$page_title = 'Artikel Opini - KSM Education';
include 'components/header.php';
include 'components/sidebar.php';
?>


    <!-- Main Content -->
    <div class="container">
      <!-- Filter & Search Section -->
      <section class="filter-section">
        <!-- Row 1: Icon Sort + Search Box -->
        <div class="filter-row-top">
          <!-- Icon Sort Dropdown -->
          <div class="sort-dropdown">
            <button class="btn-icon-sort" type="button" id="btnSort">
              <i data-feather="filter"></i>
            </button>
            <div class="sort-menu" id="sortMenu">
              <button data-sort="newest" class="sort-item active">
                <i data-feather="clock"></i>
                Terbaru
              </button>
              <button data-sort="oldest" class="sort-item">
                <i data-feather="calendar"></i>
                Terlama
              </button>
              <button data-sort="title" class="sort-item">
                <i data-feather="type"></i>
                Judul A-Z
              </button>
              <button data-sort="views" class="sort-item">
                <i data-feather="eye"></i>
                Paling Populer
              </button>
            </div>
          </div>

          <!-- Search Box -->
          <div class="search-box">
            <i data-feather="search"></i>
            <input type="text" placeholder="Cari opini..." id="searchInput" />
          </div>
        </div>

        <!-- Row 2: Total Counter -->
        <div class="filter-row-bottom">
          <div class="filter-stats">
            <span id="totalJournals">0</span> Artikel
          </div>
        </div>
      </section>

      <!-- Back Button -->
      <section class="back-section">
        <a href="./dashboard_admin.php" class="btn-back">
          <i data-feather="arrow-left"></i>
        </a>
      </section>

      <!-- Opinion List Section -->
      <section id="journal" class="journal-list-full">
        <div id="journalContainer" class="list-view">
          <!-- Opinion items will be generated by jurnal.js -->
        </div>
      </section>

      <!-- Pagination (optional, bisa dihapus kalau ga pake) -->
      <section class="pagination-section">
        <div id="pagination" class="pagination"></div>
      </section>
    </div>

    <!-- Share Modal -->
    <div id="shareModal" class="modal">
      <div class="modal-overlay"></div>
      <div class="modal-content" style="max-width: 400px">
        <button type="button" class="close-modal" onclick="closeShareModal()">
          <i data-feather="x"></i>
        </button>
        <h2 style="margin-bottom: 20px">Bagikan Artikel</h2>
        <div style="display: flex; flex-direction: column; gap: 12px">
          <input
            type="text"
            id="shareUrlInput"
            readonly
            style="
              padding: 12px;
              border: 1px solid #ddd;
              border-radius: 6px;
              font-size: 14px;
            "
          />
          <button onclick="copyShareLink()" class="share-btn copy">
            <i data-feather="copy"></i> Copy Link
          </button>
          <button onclick="shareToWhatsApp()" class="share-btn wa">
            <i data-feather="message-circle"></i> Share ke WhatsApp
          </button>
          <button onclick="shareToFacebook()" class="share-btn fb">
            <i data-feather="facebook"></i> Share ke Facebook
          </button>
          <button onclick="shareToTwitter()" class="share-btn x">
            <i data-feather="x"></i> Share ke X
          </button>
        </div>
      </div>
    </div>

    <!-- Edit Modal (optional, kalau mau edit opini di halaman ini) -->
    <div id="editModal" class="modal">
      <div class="modal-overlay"></div>
      <div class="modal-content">
        <button id="closeEditModal" type="button" class="modal-close">
          &times;
        </button>
        <h2>Edit Opini</h2>
        <form id="editForm">
          <input type="hidden" id="editJournalId" />
          <div class="form-group">
            <label for="editJudulJurnal">Judul Opini</label>
            <input type="text" id="editJudulJurnal" required />
          </div>
          <div class="form-group">
            <label for="editEmail">Email</label>
            <input type="email" id="editEmail" />
          </div>
          <div class="form-group">
            <label for="editKontak">Kontak</label>
            <input type="text" id="editKontak" />
          </div>
          <div class="form-group">
            <label>Tag/Keyword (Opsional)</label>
            <div id="editTagsContainer" class="tags-container"></div>
            <div style="display: flex; gap: 10px; margin-top: 10px">
              <input type="text" id="editTagInput" placeholder="Masukkan tag (Enter untuk tambah)" style="flex: 1; padding: 10px; border: 1px solid #e0e0e0; border-radius: 6px;" />
              <button type="button" id="editAddTagBtn" class="btn-secondary">Tambah Tag</button>
            </div>
          </div>
          <div class="form-group">
            <label>Nama Penulis<span class="required">*</span></label>
            <div id="editAuthorsContainer"></div>
            <button
              type="button"
              id="editAddAuthorBtn"
              class="btn-secondary"
              style="margin-top: 10px"
            >
              <i data-feather="plus"></i> Tambah Penulis
            </button>
          </div>
          <div class="form-group">
            <label for="editAbstrak">Deskripsi</label>
            <textarea id="editAbstrak" rows="5"></textarea>
          </div>
          <div class="form-group">
            <label for="editFileInput">File PDF (opsional)</label>
            <input type="file" id="editFileInput" accept="application/pdf" />
          </div>
          <div class="form-group">
            <label for="editCoverInput">Cover (opsional)</label>
            <input type="file" id="editCoverInput" accept="image/*" />
          </div>
          <div class="form-actions">
            <button type="button" id="cancelEdit" class="btn-secondary">
              Batal
            </button>
            <button type="submit" class="btn-primary">Simpan Perubahan</button>
          </div>
        </form>
      </div>
    </div>

    <!-- Login Modal -->
    <div id="loginModal" class="modal">
      <div class="modal-overlay"></div>
      <div class="modal-content login-container">
        <button type="button" class="close-modal" id="closeLoginModal">
          <i data-feather="x"></i>
        </button>
        <div class="login-header">
          <img src="../assets/main_logo.png" alt="KSM Education Logo" class="login-logo" />
          <h2>ADMIN LOGIN</h2>
          <p style="color: #666; font-size: 14px; margin-top: 8px">Login sebagai Administrator</p>
        </div>
        <form id="loginForm" class="login-form">
          <div class="form-group">
            <input type="email" id="loginEmail" placeholder="Masukan Email Admin" required />
          </div>
          <div class="form-group password-group">
            <input type="password" id="loginPassword" placeholder="Masukan Password" required />
            <button type="button" class="toggle-password" id="togglePassword">
              <i data-feather="eye" id="eyeIcon"></i>
            </button>
          </div>
          <div class="form-options">
            <label class="remember-me">
              <input type="checkbox" id="rememberMe" />
              <span>Remember Me</span>
            </label>
            <a href="#" class="forgot-password">Forgot Password?</a>
          </div>
          <button type="submit" class="btn-login">MASUK</button>
        </form>
      </div>
    </div>

    <!-- Scripts -->
    
<?php
$extra_scripts = <<<'EOT'
<script src="../js/api.js"></script>
    <script src="../js/statistic.js"></script>
    <script src="../js/file_upload.js"></script>
    <script src="../js/pagination_admin.js?v=20260321"></script>
    <script src="../js/jurnal.js?v=20260321"></script>
    <script src="../js/mobile_menu.js"></script>
    <script src="../js/login.js"></script>
    <script src="../js/social.js"></script>
    <script src="../js/custom_alerts.js"></script>
    <script src="../js/script.js"></script>

    <script>
      feather.replace();
    </script>
  
EOT;
include 'components/footer.php';
?>
