<?php
$page_title = 'KSM Education';
$base_css = '<link rel="stylesheet" href="../styles/dashboard_user.css?v=202501111545" />';
include 'components/header.php';
include 'components/navbar.php';
?>


    <!-- Main Content -->
    <div class="container">
      <!-- Statistics Section -->
      <section class="statistics">
        <h2>Statistik</h2>
        <div class="stats-grid">
          <div class="stat-card">
            <div class="stat-icon">
              <i data-feather="bar-chart-2"></i>
            </div>
            <div class="stat-number" id="articleCount">0</div>
            <div class="stat-label">ARTIKEL</div>
          </div>
          <div class="stat-card">
            <div class="stat-icon">
              <i data-feather="eye"></i>
            </div>
            <div class="stat-number" id="visitorCount">0</div>
            <div class="stat-label">Pengunjung</div>
          </div>
        </div>
      </section>

      <!-- Articles Section -->
      <section class="articles-section">
        <h2>Artikel Terbaru</h2>
        <div class="articles-grid" id="articlesGrid">
          <!-- Articles will be generated by JavaScript -->
        </div>
        <div id="latestArticlesNavUser"></div>
      </section>

      <!-- Categories Section -->
      <section class="categories-section">
        <h2>Kategori Populer</h2>
        <div class="categories-grid">
          <div class="category-card">
            <span class="category-name">Social</span>
            <span class="category-count">(17)</span>
          </div>
          <div class="category-card">
            <span class="category-name">International</span>
            <span class="category-count">(84)</span>
          </div>
          <div class="category-card">
            <span class="category-name">Crime</span>
            <span class="category-count">(32)</span>
          </div>
          <div class="category-card">
            <span class="category-name">Accident</span>
            <span class="category-count">(24)</span>
          </div>
          <div class="category-card">
            <span class="category-name">Political</span>
            <span class="category-count">(155)</span>
          </div>
          <div class="category-card">
            <span class="category-name">Sports</span>
            <span class="category-count">(1952)</span>
          </div>
          <div class="category-card">
            <span class="category-name">Health</span>
            <span class="category-count">(143)</span>
          </div>
          <div class="category-card">
            <span class="category-name">Education</span>
            <span class="category-count">(91)</span>
          </div>
        </div>
      </section>

    </div>

    <!-- Main Footer -->
    

    <!-- Scripts -->
    
<?php
$extra_scripts = <<<'EOT'
<script src="../js/script.js?v=2025112910"></script>
    <script src="../js/custom_alerts.js"></script>
    <script src="../js/statistic.js?v=20251130"></script>
    <script src="../js/jurnal.js?v=20260321"></script>
    <script src="../js/opinions_manager.js"></script>
    <script src="../js/file_upload.js"></script>
    <script src="../js/dashboard_user.js?v=20260321"></script>
    <script src="../js/mobile_menu.js?v=20251130"></script>
    <script>
      feather.replace();
    </script>
  
EOT;
include 'components/footer.php';
?>
