<?php
$page_title = 'Daftar Jurnal - KSM Education';
$base_css = '<link rel="stylesheet" href="../styles/admin.css" />';
include 'components/header.php';
include 'components/navbar.php';
?>


    <!-- Main Content -->
    <div class="container">
      <!-- Filter & Search Section -->
      <section class="filter-section">
        <!-- Row 1: Icon Sort + Search Box -->
        <div class="filter-row-top">
          <!-- Icon Sort Dropdown -->
          <div class="sort-dropdown">
            <button class="btn-icon-sort" type="button" id="btnSort">
              <i data-feather="filter"></i>
            </button>
            <div class="sort-menu" id="sortMenu">
              <button data-sort="newest" class="sort-item active">
                <i data-feather="clock"></i>
                Terbaru
              </button>
              <button data-sort="oldest" class="sort-item">
                <i data-feather="calendar"></i>
                Terlama
              </button>
              <button data-sort="title" class="sort-item">
                <i data-feather="type"></i>
                Judul A-Z
              </button>
              <button data-sort="views" class="sort-item">
                <i data-feather="eye"></i>
                Paling Populer
              </button>
            </div>
          </div>

          <!-- Search Box -->
          <div class="search-box">
            <i data-feather="search"></i>
            <input type="text" placeholder="Cari jurnal..." id="searchInput" />
          </div>
        </div>

        <!-- Row 2: Total Counter -->
        <div class="filter-row-bottom">
          <div class="filter-stats">
            <span id="totalJournals">0</span> Artikel
          </div>
        </div>
      </section>

      <!-- Back Button -->
      <section class="back-section">
        <a href="./dashboard_user.php" class="btn-back">
          <i data-feather="arrow-left"></i>
        </a>
      </section>

      <!-- Journal List Section -->
      <section id="journal" class="journal-list-full">
        <div id="journalContainer" class="list-view">
          <!-- Journal items will be generated by pagination.js -->
        </div>
      </section>

      <!-- Pagination -->
      <section class="pagination-section">
        <div id="pagination" class="pagination"></div>
      </section>
    </div>

    <!-- Main Footer -->
    
    
    <!-- Scripts -->
    
<?php
$extra_scripts = <<<'EOT'
<script src="../js/script.js"></script>
    <script src="../js/custom_alerts.js"></script>
    <script src="../js/pagination_user.js?v=20260321"></script>
    <script src="../js/mobile_menu.js"></script>
    <script>
      feather.replace();
    </script>
  
EOT;
include 'components/footer.php';
?>
